// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Infrastructure.Data;

#nullable disable

namespace ProductCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241204091033_new-fores2")]
    partial class newfores2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalog.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Disco duro externo portátil de 4TB compatible con PlayStation 4. Ideal para almacenar juegos y contenido multimedia.",
                            ImageUrl = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
                            Name = "Disco Duro Externo WD 4TB para PS4",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Monitor curvado de 49 pulgadas con pantalla ultrapanorámica y frecuencia de actualización de 144Hz, ideal para juegos y productividad.",
                            ImageUrl = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
                            Name = "Monitor Curvo Samsung 49' QLED para Juegos",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
                            ImageUrl = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Name = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
                            Price = 109.95m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing.",
                            ImageUrl = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
                            Name = "Mens Casual Premium Slim Fit T-Shirts",
                            Price = 22.30m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions like hiking, camping, and more.",
                            ImageUrl = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
                            Name = "Mens Cotton Jacket",
                            Price = 55.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "The color could be slightly different between on the screen and in practice.",
                            ImageUrl = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
                            Name = "Mens Casual Slim Fit",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Inspired by the mythical water dragon that protects the ocean's pearl.",
                            ImageUrl = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
                            Name = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
                            Price = 695.00m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Satisfaction Guaranteed. Return or exchange any order within 30 days.",
                            ImageUrl = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
                            Name = "Solid Gold Petite Micropave",
                            Price = 168.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her.",
                            ImageUrl = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
                            Name = "White Gold Plated Princess",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel.",
                            ImageUrl = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
                            Name = "Pierced Owl Rose Gold Plated Stainless Steel Double",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 11,
                            Description = "USB 3.0 and USB 2.0 Compatibility. Fast data transfers and high capacity.",
                            ImageUrl = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
                            Name = "WD 2TB Elements Portable External Hard Drive - USB 3.0",
                            Price = 64.00m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Easy upgrade for faster boot up, shutdown, application load and response.",
                            ImageUrl = "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
                            Name = "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
                            Price = 109.00m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Remarkable transfer speeds and improved overall system performance.",
                            ImageUrl = "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
                            Name = "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
                            Price = 109.00m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Expand your PS4 gaming experience with high capacity and fast setup.",
                            ImageUrl = "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
                            Name = "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
                            Price = 114.00m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Full HD widescreen IPS display with Radeon FreeSync technology.",
                            ImageUrl = "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
                            Name = "Acer SB220Q bi 21.5 inches Full HD IPS Ultra-Thin Monitor",
                            Price = 599.00m
                        },
                        new
                        {
                            Id = 16,
                            Description = "144Hz curved super ultrawide monitor with QLED technology.",
                            ImageUrl = "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
                            Name = "Samsung 49-Inch Curved Gaming Monitor",
                            Price = 999.99m
                        });
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ProductCatalog.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductCatalog.Domain.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ProductCatalog.Domain.Entities.User", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
